greedy-team/mokkoji-be

src/main/java/com/greedy/mokkoji/config/JpaAuditingConfig.java, src/main/java/com/greedy/mokkoji/db/BaseTime.java, src/main/java/com/greedy/mokkoji/db/club/entity/Club.java, src/main/java/com/greedy/mokkoji/db/club/repository/ClubRepository.java, src/main/java/com/greedy/mokkoji/db/favorite/entity/Favorite.java, src/main/java/com/greedy/mokkoji/db/favorite/repository/FavoriteRepository.java, src/main/java/com/greedy/mokkoji/db/recruitment/entity/Recruitment.java, src/main/java/com/greedy/mokkoji/db/recruitment/repository/RecruitmentRepository.java, src/main/java/com/greedy/mokkoji/db/user/entity/User.java, src/main/java/com/greedy/mokkoji/db/user/repository/UserRepository.java, src/main/java/com/greedy/mokkoji/enums/ClubAffiliation.java, src/main/java/com/greedy/mokkoji/enums/ClubCategory.java
close #7 
* DB 엔티티와 Repository를 생성했습니다.
=> Feat: DB 엔티티 생성

src/main/java/com/greedy/mokkoji/db/club/repository/ClubRepository.java, src/main/java/com/greedy/mokkoji/db/favorite/repository/FavoriteRepository.java, src/main/java/com/greedy/mokkoji/db/recruitment/repository/RecruitmentRepository.java, src/main/java/com/greedy/mokkoji/db/user/repository/UserRepository.java
close #10 
* Repository에 @Repository가 작성되어 있지 않아서 이를 작성했습니다.
=> Fix: @Repository 기입

build.gradle, src/main/java/com/greedy/mokkoji/api/favorite/controller/FavoriteController.java, src/main/java/com/greedy/mokkoji/api/favorite/service/FavoriteService.java, src/main/java/com/greedy/mokkoji/db/club/entity/Club.java, src/main/java/com/greedy/mokkoji/db/favorite/repository/FavoriteRepository.java, src/main/java/com/greedy/mokkoji/enums/ClubAffiliation.java, src/main/java/com/greedy/mokkoji/enums/ClubCategory.java, src/main/java/com/greedy/mokkoji/enums/club/ClubAffiliation.java, src/main/java/com/greedy/mokkoji/enums/club/ClubCategory.java, src/main/java/com/greedy/mokkoji/enums/message/FailMessage.java, src/test/java/com/greedy/mokkoji/favorite/FavoriteTest.java
close #12
* 즐겨찾기 추가 및 삭제 API를 구현했습니다.
* API에 맞는 테스트코드를 작성했습니다.
* cmd + option + l 을 이용해서 매번 정렬을 사용해주시면 좋을 것 같습니다!
* 카테고리와 동아리 구분 Enum 타입에 TEST를 넣어놓았습니다. 이후 충돌이 날 확률이 매우 높고, 테스트가 깨질 수 있으니 이를 감안하고 리뷰해주시면 감사하겠습니다 : ) (테스트가 깨질 때는 그거에 맞추어 수정하겠습니다!)
=> Feat: 즐겨찾기 추가 및 삭제 API 구현

src/test/java/com/greedy/mokkoji/user/UserServiceTest.java
close #19
FailMessage 오류수정
따옴표 까먹어서 생긴 오류라 따옴표 붙임
=> Refactor : 자동정렬

src/main/java/com/greedy/mokkoji/api/user/controller/UserController.java
close #31
로그아웃과 사용자 정보 업데이트 시 아무 정보도 반환하지 않았는 데
공통 형식을 맞춰 null값 반환하는 로직으로 바꿈
=> Refactor : 로그인, 사용자조회 답변 공통형식 지키기

build.gradle, src/main/java/com/greedy/mokkoji/api/club/service/ClubService.java, src/main/java/com/greedy/mokkoji/api/external/AppDataS3Client.java, src/main/java/com/greedy/mokkoji/config/AwsConfig.java, src/test/java/com/greedy/mokkoji/club/ClubSearchTest.java
close #29 
* 동아리 로고 이미지의 Presigned Url을 불러오도록 코드를 작성했습니다.
=> Feat: S3 presigned url 추가

src/main/java/com/greedy/mokkoji/config/WebConfig.java
close #35 
- Intercepter를 거치지 않는 url 수정
- 잠시 cors 테스트용 url 추가
=> FIX: cors에러 해결 & inteceptor 에러 해결

src/main/java/com/greedy/mokkoji/config/WebConfig.java
close #37 
- cors 허용해주는 url 알맞게 변경
- 브라우저 캐시 시간 늘림
- ssl 인증서 처리를 해줘서 http 요청이 오면 https로 리다이렉트 되서 프론트 로컬에서 http로 요청 날려서 테스트하면 cors에러 날 것임
=> [FIX]: cors 에러 해결

src/test/java/com/greedy/mokkoji/external/SejongLoginClientTest.java, src/test/java/com/greedy/mokkoji/user/UserServiceTest.java
=> Feat: 회원정보 업데이트 test 코드 작성 /#43

src/test/java/com/greedy/mokkoji/external/SejongLoginClientTest.java, src/test/java/com/greedy/mokkoji/user/TokenServiceTest.java, src/test/java/com/greedy/mokkoji/user/UserServiceTest.java
=> Feat: access토큰 재발급, 로그아웃 test 코드 /#41

src/test/java/com/greedy/mokkoji/external/SejongLoginClientTest.java
=> Feat: yml파일 변수명 수정 /#47

src/main/java/com/greedy/mokkoji/api/auth/controller/argumentResolver/UserAuthArgumentResolver.java, src/main/java/com/greedy/mokkoji/api/jwt/BearerAuthExtractor.java, src/main/java/com/greedy/mokkoji/api/jwt/JwtUtil.java, src/main/java/com/greedy/mokkoji/api/user/controller/UserController.java, src/main/java/com/greedy/mokkoji/api/user/service/UserService.java, src/main/java/com/greedy/mokkoji/common/handler/JwtAuthInterceptor.java, src/main/java/com/greedy/mokkoji/enums/message/FailMessage.java
close #50 
- bearer를 추출하는 과정을 class화 시켰습니다.
- 중복 예외처리가 되는 코드를 삭제하였습니다.
- userController에서 바로 토큰 서비스로 접근하는 것은 이전 코드 방향성과 다르다 생각하여 userService를 통해 tokenService를 사용하도록 수정하였습니다.
=> Refactor: 인증 Bearer처리 과정 리팩토링

build.gradle, src/main/java/com/greedy/mokkoji/api/user/dto/request/UpdateUserInformationRequest.java, src/test/java/com/greedy/mokkoji/MokkojiApplicationTests.java, src/test/java/com/greedy/mokkoji/common/AbstractTest.java, src/test/java/com/greedy/mokkoji/common/ControllerTest.java, src/test/java/com/greedy/mokkoji/common/fixture/Fixture.java, src/test/java/com/greedy/mokkoji/external/SejongLoginClientTest.java, src/test/java/com/greedy/mokkoji/user/controller/UserControllerTest.java, src/test/java/com/greedy/mokkoji/user/service/TokenServiceTest.java, src/test/java/com/greedy/mokkoji/user/service/UserServiceTest.java
close #54 
- 기본 공통 테스트 코드 작성
- user api 테스트 코드 작성
=> Feat:User API Controller 테스트 코드 구현, Controller 공통 테스트 코드 작성

src/test/java/com/greedy/mokkoji/club/controller/ClubControllerTest.java, src/test/java/com/greedy/mokkoji/club/service/ClubServiceTest.java, src/test/java/com/greedy/mokkoji/common/AbstractTest.java, src/test/java/com/greedy/mokkoji/common/ControllerTest.java, src/test/java/com/greedy/mokkoji/common/fixture/Fixture.java, src/test/java/com/greedy/mokkoji/user/controller/UserControllerTest.java
close #52
동아리 API Controller에 대한 테스트를 구현하였습니다.
-
=> Feat: 동아리 API Controller 테스트 구현

src/main/java/com/greedy/mokkoji/enums/club/ClubAffiliation.java, src/main/java/com/greedy/mokkoji/enums/club/ClubCategory.java, src/test/java/com/greedy/mokkoji/club/service/ClubServiceTest.java, src/test/java/com/greedy/mokkoji/favorite/FavoriteTest.java
close #66 
- 동아리 afflication 및 category descritption 변경
=> Fix: 동아리 afflication 및 category descritption 변경

build.gradle
close #77 
- 프로메테우스 모니터링 설정 추가
=> Feat: 프로메테우스 모니터링 설정 추가

build.gradle, docker-compose.yml
=> Feat: 프로메테우스를 위한 도커 컨테이너 포트 개방

docker-compose.yml
=> Fix: 모니터링 포트 blue green 무중단 배포를 위해 수정

build.gradle, src/test/java/com/greedy/mokkoji/club/controller/ClubControllerTest.java, src/test/java/com/greedy/mokkoji/common/ControllerTest.java, src/test/java/com/greedy/mokkoji/favorite/controller/FavoriteControllerTest.java, src/test/java/com/greedy/mokkoji/favorite/servcie/FavoriteServiceTest.java, src/test/java/com/greedy/mokkoji/user/controller/AuthInterceptorTest.java, src/test/java/com/greedy/mokkoji/user/controller/UserControllerTest.java
close #64 
- auth controller test 리팩토링
- favorite controller test 구현
-  jacoco 테스트 커버리지 확인할 수 있도록 적용
=> Feat: favorite controller test 구현, auth controller test 리팩토링, jacoco 테스트 커버리지 확인할 수 있도록 적용

src/main/java/com/greedy/mokkoji/api/notification/service/EmailNotificationChannel.java, src/main/java/com/greedy/mokkoji/api/notification/service/NotificationChannel.java, src/main/java/com/greedy/mokkoji/api/notification/service/NotificationService.java, src/test/java/com/greedy/mokkoji/notification/EmailNotificationTest.java, src/test/java/com/greedy/mokkoji/notification/NotificationTest.java
close #72 
- 이메일 형태를 단순 문자열에서 html로 변경하였습니다.
=> Refactor: 이메일 알림 메세지 형태 수정

src/main/java/com/greedy/mokkoji/db/club/repository/ClubRepositoryImpl.java, src/test/java/com/greedy/mokkoji/club/controller/ClubControllerTest.java, src/test/java/com/greedy/mokkoji/common/fixture/Fixture.java
close #89 
- 동아리들 중복되서 조회되는 문제 해결
- TODO 작성
- 테스트 가짜 객체 값 상수화
=> Fix: 동아리들 중복되서 조회되는 문제 해결

src/main/java/com/greedy/mokkoji/db/BaseTime.java, src/main/java/com/greedy/mokkoji/db/club/entity/Club.java, src/main/java/com/greedy/mokkoji/db/recruitment/entity/Recruitment.java, src/main/java/com/greedy/mokkoji/db/recruitment/entity/RecruitmentImage.java, src/main/java/com/greedy/mokkoji/db/user/entity/User.java, src/main/java/com/greedy/mokkoji/enums/user/UserRole.java
close #95 
* erd 수정에 따른 엔티티 필드를 수정하거나 추가했습니다.
* 링크 참고하면서 빠진 부분이나 어색한 부분 잘못된 부분이 있는지 확인해주시면 감사하겠습니다 : )
https://www.erdcloud.com/d/C8jS48dwMBdsmiuPf
=> Fix: ERD 수정에 따른 엔티티 수정

src/main/java/com/greedy/mokkoji/api/report/controller/ReportController.java, src/main/java/com/greedy/mokkoji/api/report/dto/request/ReportRequest.java, src/main/java/com/greedy/mokkoji/api/report/service/ReportService.java, src/main/java/com/greedy/mokkoji/db/report/entity/Report.java, src/main/java/com/greedy/mokkoji/db/report/repository/ReportRepository.java, src/main/java/com/greedy/mokkoji/enums/report/ReportType.java
close #111 
동아리 신고 API를 구현했습니다.
- 동아리 신고 내역 조회나, 동아리 신고 내용 삭제 등(권한: Admin)의 API는 굳이 필요하지 않다고 생각하시나요? 의견이 궁금합니다!
- Enum은 그냥 막연히 생각해서 적어봤는데, 수정이 필요해보이거나 추가해야할 항목이 있다면 말씀주세요!
=> Feat: 동아리 신고 API 구현

.github/workflows/CD-dev.yml, src/main/java/com/greedy/mokkoji/api/user/service/TokenService.java, src/main/java/com/greedy/mokkoji/config/RedisConfig.java, src/main/java/com/greedy/mokkoji/db/user/entity/User.java, src/main/java/com/greedy/mokkoji/db/user/repository/RedisRepository.java, src/main/java/com/greedy/mokkoji/db/user/repository/UserRepository.java
close #133 
* redis 오류 해결을 위해 의심되는 미사용 필드를 제거했습니다.
* Redis 관련 설정과 RedisRepository를 생성했습니다.
=> Hotfix: 필요없는 유저 필드 제거

src/main/java/com/greedy/mokkoji/api/user/controller/UserController.java, src/main/java/com/greedy/mokkoji/api/user/dto/resopnse/UserManageClubResponse.java, src/main/java/com/greedy/mokkoji/api/user/dto/resopnse/UserManageClubsResponse.java, src/main/java/com/greedy/mokkoji/api/user/service/UserService.java, src/main/java/com/greedy/mokkoji/db/club/repository/ClubRepository.java
close #136
* user가 관리하는 동아리 리스트 반환 api  만들었습니다.
=> Feat : user가 관리하는 동아리 리스트 반환 api 만들기

src/main/java/com/greedy/mokkoji/api/club/controller/ClubController.java, src/main/java/com/greedy/mokkoji/api/club/dto/club/request/ClubCreateRequest.java, src/main/java/com/greedy/mokkoji/api/club/dto/club/request/ClubUpdateRequest.java, src/main/java/com/greedy/mokkoji/api/club/dto/club/response/ClubDetailResponse.java, src/main/java/com/greedy/mokkoji/api/club/dto/club/response/ClubResponse.java, src/main/java/com/greedy/mokkoji/api/club/service/ClubService.java, src/main/java/com/greedy/mokkoji/db/club/entity/Club.java, src/test/java/com/greedy/mokkoji/club/service/ClubServiceTest.java, src/test/java/com/greedy/mokkoji/favorite/servcie/FavoriteServiceTest.java
close #135 
- api 명세와 맞지 않는 부분이 존재하여 동아리 관련 DTO 값들을 수정했습니다.
- 같은 의미를 가진 DTO 내에서도, 다른 네이밍으로 되어있는 경우를 발견하여 db와 같은 네이밍으로 통일했습니다.
- 동아리 api 최종 점검 차, postman으로 다양한 상황을 대입해보며 검증 완료했습니다.
2차 스트린트에서 새로 적용한 부분 테스트 코드를 작성해야합니다.
해당 부분은 따로 이슈를 파서 진행하겠습니다.
=> Refactor: Club api 리팩토링 진행

src/main/java/com/greedy/mokkoji/api/user/service/TokenService.java, src/main/java/com/greedy/mokkoji/config/RedisConfig.java
close #147 
* refreshToken의 키 형식이 맞지 않아 이를 수정했습니다.
=> Hotfix: 리프레시 토큰 키 형식 변경

src/main/java/com/greedy/mokkoji/api/favorite/dto/response/RecruitClubsResponse.java, src/main/java/com/greedy/mokkoji/api/favorite/service/FavoriteService.java
=> Refactor : 즐겨찾기한 동아리 모집글 조회 시 clubId도 함께 반환
